-- Seed exercise library with full metadata.
-- Safe to re-run: ON CONFLICT updates metadata on existing rows.

INSERT INTO public.exercises (name, training_quality, muscle_group, movement_pattern, intensity_tier, bilateral, equipment, notes, source)
VALUES
  ('Back Squat', 'max_strength', 'quads', 'squat', 'high', true, ARRAY['barbell', 'rack']::text[], NULL, 'Andy''s library'),
  ('Front Squat', 'max_strength', 'quads', 'squat', 'high', true, ARRAY['barbell', 'rack']::text[], NULL, 'Andy''s library'),
  ('Bulgarian Split Squat', 'max_strength', 'quads', 'lunge', 'high', false, ARRAY['dumbbells', 'bench']::text[], NULL, 'Andy''s library'),
  ('ATG Split Squat', 'max_strength', 'quads', 'lunge', 'high', false, ARRAY['dumbbells']::text[], 'Full ROM knee-over-toe', 'Andy''s library'),
  ('Trap Bar Deadlift', 'max_strength', 'hamstrings', 'hinge', 'high', true, ARRAY['trap bar']::text[], NULL, 'Andy''s library'),
  ('Pause Squat', 'max_strength', 'quads', 'squat', 'high', true, ARRAY['barbell', 'rack']::text[], '3s pause in hole. RFD from dead stop', 'VJB'),
  ('Paused Box Squat', 'strength_speed', 'quads', 'squat', 'high', true, ARRAY['barbell', 'rack', 'box']::text[], 'Sit on box, pause 1s, EXPLODE. VJB speed-strength', 'VJB'),
  ('VMO Squat', 'max_strength', 'quads', 'squat', 'medium', true, ARRAY['barbell']::text[], NULL, 'Andy''s library'),
  ('Barbell Hip Thrust', 'max_strength', 'glutes', 'hinge', 'high', true, ARRAY['barbell', 'bench']::text[], 'Full hip extension at top', 'Andy''s library + VJB'),
  ('Glute-Ham Raise', 'max_strength', 'hamstrings', 'hinge', 'medium', true, ARRAY['GHR machine']::text[], 'If no GHR, use Nordic curl', 'VJB'),
  ('Good Morning', 'max_strength', 'hamstrings', 'hinge', 'medium', true, ARRAY['barbell']::text[], 'Hip hinge variation', 'VJB'),
  ('Nordic Hamstring Curl', 'max_strength', 'hamstrings', 'hinge', 'medium', true, ARRAY['bodyweight']::text[], 'Eccentric control emphasis', 'Andy''s library + VJB'),
  ('Quad Extension', 'max_strength', 'quads', 'squat', 'low', true, ARRAY['machine']::text[], 'Machine isolation', 'Andy''s library'),
  ('RDL', 'max_strength', 'hamstrings', 'hinge', 'high', true, ARRAY['barbell']::text[], 'Compound hip hinge. Use straps for wrist', 'Andy''s library + VJB'),
  ('Reverse Hyperextension', 'max_strength', 'glutes', 'hinge', 'medium', true, ARRAY['reverse hyper machine']::text[], 'VJB hip strength exercise', 'VJB'),
  ('Seated Calf Raise', 'max_strength', 'calves', 'squat', 'low', true, ARRAY['machine']::text[], 'Slow eccentric, full ROM', 'VJB'),
  ('Standing Calf Raise', 'max_strength', 'calves', 'squat', 'low', true, ARRAY['machine']::text[], 'Full ROM, pause at bottom. Higher reps 15-20', 'Andy''s library + VJB'),
  ('Tibialis Raise', 'max_strength', 'calves', 'squat', 'low', true, ARRAY['tib bar']::text[], 'Bulletproofing exercise', 'Andy''s library'),
  ('Cossack Squat', 'max_strength', 'hips', 'squat', 'medium', true, ARRAY['bodyweight']::text[], 'Mobility + strength combo', 'Andy''s library'),
  ('Pistol Squat', 'max_strength', 'quads', 'squat', 'high', false, ARRAY['bodyweight']::text[], 'Slow eccentric, heavy resistance on down', 'Andy''s library'),
  ('Poliquin Step-Up', 'max_strength', 'quads', 'lunge', 'low', false, ARRAY['bodyweight']::text[], 'Slow controlled step-up for knee health', 'Andy''s library'),
  ('Reverse Sled', 'max_strength', 'quads', 'squat', 'low', true, ARRAY['sled']::text[], 'Backward sled drag for knee health', 'Andy''s library'),
  ('Sissy Squat', 'max_strength', 'quads', 'squat', 'medium', true, ARRAY['bodyweight']::text[], 'Knee health exercise', 'Andy''s library'),
  ('Hang Power Clean', 'strength_speed', 'full_body', 'olympic', 'high', true, ARRAY['barbell']::text[], 'Hip-dominant loaded RFD', 'VJB + THP'),
  ('Hang Power Snatch', 'strength_speed', 'full_body', 'olympic', 'high', true, ARRAY['barbell']::text[], 'Lighter than cleans, higher bar speed. Wrist-friendly', 'VJB + THP'),
  ('Power Clean', 'strength_speed', 'full_body', 'olympic', 'high', true, ARRAY['barbell']::text[], 'Includes hang, power, and block variations', 'Andy''s library + THP'),
  ('Power Snatch', 'strength_speed', 'full_body', 'olympic', 'high', true, ARRAY['barbell']::text[], 'Includes hang, power, and muscle snatch variations', 'Andy''s library + THP'),
  ('Clean Deadlift', 'max_strength', 'hamstrings', 'hinge', 'high', true, ARRAY['barbell']::text[], 'Clean-grip pull position. Straps', 'THP'),
  ('DB Two-Hand Swing', 'strength_speed', 'glutes', 'hinge', 'medium', true, ARRAY['dumbbell']::text[], 'VJB loaded hip RFD exercise', 'VJB'),
  ('Speed Squat', 'strength_speed', 'quads', 'squat', 'medium', true, ARRAY['barbell', 'rack']::text[], '60% 1RM, max concentric speed. 5-6x2', 'VJB'),
  ('Barbell Skip', 'strength_speed', 'calves', 'plyometric', 'medium', true, ARRAY['barbell']::text[], 'VJB loaded ankle RFD exercise', 'VJB'),
  ('Pogo Jumps (ankle hops)', 'reactive', 'calves', 'plyometric', 'low', true, ARRAY['bodyweight']::text[], 'Minimize ground contact. Tendon stiffness', 'Andy''s library + VJB'),
  ('Jump Rope', 'reactive', 'calves', 'plyometric', 'low', true, ARRAY['jump rope']::text[], 'Low-intensity coordination', 'Andy''s library'),
  ('Rhythmic Jumps', 'reactive', 'calves', 'plyometric', 'low', true, ARRAY['bodyweight']::text[], 'Single & double leg. Short SSC', 'Andy''s library'),
  ('Single-Leg Pogos', 'reactive', 'calves', 'plyometric', 'medium', false, ARRAY['bodyweight']::text[], 'Jump up and down on single leg', 'Andy''s library'),
  ('Tuck Jumps', 'reactive', 'quads', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], 'Max height. Drive knees up maximally', 'Andy''s library + VJB'),
  ('Box Jump', 'reactive', 'quads', 'plyometric', 'medium', true, ARRAY['box']::text[], 'Box height stimulates the height', 'Andy''s library'),
  ('Broad Jump', 'reactive', 'glutes', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], 'Max distance. VJB hip speed-strength', 'Andy''s library + VJB'),
  ('Standing Broad Jump', 'reactive', 'glutes', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], 'VJB hip speed-strength exercise', 'VJB'),
  ('Triple Broad Jump', 'reactive', 'glutes', 'plyometric', 'high', true, ARRAY['bodyweight']::text[], '3 consecutive jumps for max total distance', 'VJB'),
  ('Lunge Jumps (alternating)', 'reactive', 'quads', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], 'Jump as high as possible from lunge position', 'VJB'),
  ('Lateral Cone/Barrier Jumps', 'reactive', 'hips', 'plyometric', 'medium', true, ARRAY['cones']::text[], 'Mid-shin height obstacle. Quick feet', 'Andy''s library + VJB'),
  ('Reactive Hurdle Jumps', 'reactive', 'full_body', 'plyometric', 'medium', true, ARRAY['hurdles']::text[], 'Jump combos with hurdles', 'Andy''s library'),
  ('Weighted Squat Jump', 'speed_strength', 'quads', 'plyometric', 'high', true, ARRAY['barbell']::text[], '15-30% squat max. Pause-reset each rep', 'Andy''s library + VJB'),
  ('Seated Box Jump', 'reactive', 'quads', 'plyometric', 'medium', true, ARRAY['box']::text[], 'Start sitting, eliminates SSC', 'Andy''s library + VJB'),
  ('Step-Up Jump', 'reactive', 'quads', 'plyometric', 'medium', false, ARRAY['box']::text[], 'Step up on a box then jump', 'Andy''s library'),
  ('Single-Leg Elevated Jump', 'reactive', 'quads', 'plyometric', 'high', false, ARRAY['TRX', 'bench']::text[], 'Elevate leg on TRX/bench, single leg jump', 'Andy''s library'),
  ('Max Intent Approach Jumps', 'reactive', 'full_body', 'plyometric', 'high', true, ARRAY['bodyweight']::text[], 'Run and jump for max height', 'Andy''s library + THP'),
  ('Depth Jump', 'reactive', 'full_body', 'plyometric', 'max', true, ARRAY['box']::text[], 'Drop from box and jump. Find optimal height per VJB protocol', 'Andy''s library + VJB + THP'),
  ('Drop Jump (absorb)', 'reactive', 'full_body', 'plyometric', 'high', true, ARRAY['box']::text[], 'Drop from box and absorb impact. Landing mechanics', 'Andy''s library + THP'),
  ('Altitude Drop', 'reactive', 'full_body', 'plyometric', 'max', true, ARRAY['box']::text[], 'Drop from height, absorb only. Precursor to depth jump', 'VJB + THP'),
  ('Alternate-Leg Bounds', 'reactive', 'glutes', 'plyometric', 'high', true, ARRAY['bodyweight']::text[], 'Exaggerated sprint strides. 25-30 yd', 'VJB'),
  ('Single-Leg Bounds', 'reactive', 'glutes', 'plyometric', 'high', false, ARRAY['bodyweight']::text[], 'VJB: particularly helpful for single leg jumps', 'VJB'),
  ('Single-Leg Skips / Bounds', 'reactive', 'glutes', 'plyometric', 'medium', false, ARRAY['bodyweight']::text[], 'VJB: next best plyo after depth jumps', 'Andy''s library + VJB'),
  ('Skipping for Height', 'reactive', 'calves', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], 'Max height each skip. Rhythm work', 'THP'),
  ('Skipping for Distance', 'reactive', 'glutes', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], 'Max distance per skip', 'VJB'),
  ('Sprints', 'reactive', 'full_body', 'plyometric', 'high', true, ARRAY['bodyweight']::text[], '20-40 yd. Approach speed development', 'Andy''s library + THP'),
  ('Approach Jumps', 'skill', 'full_body', 'plyometric', 'high', true, ARRAY['bodyweight']::text[], '2-foot approach jump. Work penultimate step + arm swing', 'THP'),
  ('Curved Approach Jumps', 'skill', 'full_body', 'plyometric', 'high', true, ARRAY['bodyweight']::text[], 'Slight curve for lateral/rotational advantage', 'THP'),
  ('Short Approach Jumps', 'skill', 'full_body', 'plyometric', 'medium', true, ARRAY['bodyweight']::text[], '3-4 step approach. Volleyball style', 'THP'),
  ('Dunk Attempts', 'skill', 'full_body', 'plyometric', 'high', true, ARRAY['basketball', 'rim']::text[], 'Sport-specific practice. Film every session', 'THP'),
  ('Bench Press', 'max_strength', 'chest', 'push', 'high', true, ARRAY['barbell', 'bench']::text[], NULL, 'Andy''s library'),
  ('Weighted Pull-Up', 'max_strength', 'back', 'pull', 'high', true, ARRAY['pull-up bar', 'belt']::text[], 'Use straps for wrist', 'Andy''s library'),
  ('Weighted Chin-Up', 'max_strength', 'back', 'pull', 'high', true, ARRAY['pull-up bar', 'belt']::text[], 'Use straps for wrist. Add weight when all sets clean', 'Andy''s library'),
  ('Weighted Dips', 'max_strength', 'chest', 'push', 'high', true, ARRAY['dip bars', 'belt']::text[], 'Stop if shoulder pain', 'Andy''s library'),
  ('Seated Row', 'max_strength', 'back', 'pull', 'medium', true, ARRAY['cable machine']::text[], NULL, 'Andy''s library'),
  ('Push Press', 'strength_speed', 'shoulders', 'push', 'high', true, ARRAY['barbell']::text[], 'Leg drive emphasis. Replaces jerk for shoulder safety', 'Andy''s library + THP'),
  ('Barbell Row', 'max_strength', 'back', 'pull', 'medium', true, ARRAY['barbell']::text[], 'Use straps', NULL),
  ('Behind-the-Neck Push Press', 'strength_speed', 'shoulders', 'push', 'medium', true, ARRAY['barbell']::text[], 'Use light weight to start', 'Andy''s library'),
  ('Bench Press (unbroken)', 'strength_speed', 'chest', 'push', 'medium', true, ARRAY['barbell', 'bench', 'pad']::text[], 'Use a pad on chest. Speed reps', 'Andy''s library'),
  ('Drop Rows', 'strength_speed', 'back', 'pull', 'medium', true, ARRAY['dumbbells', 'bench']::text[], 'Chest against bench, drop weight row', 'Andy''s library'),
  ('Explosive Pull-Up', 'strength_speed', 'back', 'pull', 'medium', true, ARRAY['pull-up bar']::text[], 'Speed pull-ups', 'Andy''s library'),
  ('Explosive Push-Up', 'speed_strength', 'chest', 'push', 'medium', true, ARRAY['bodyweight']::text[], 'Clap or hand-release variant', 'Andy''s library'),
  ('Med Ball Push', 'speed_strength', 'chest', 'push', 'medium', true, ARRAY['med ball']::text[], 'Explosive med ball push', 'Andy''s library'),
  ('DB Shoulder Press', 'max_strength', 'shoulders', 'push', 'medium', false, ARRAY['dumbbells']::text[], 'Neutral grip option for shoulder health', 'Andy''s library'),
  ('DB Shoulder Raise', 'max_strength', 'shoulders', 'push', 'low', false, ARRAY['dumbbells']::text[], 'Lateral delt isolation', 'Andy''s library'),
  ('Battle Ropes', 'speed_strength', 'shoulders', 'push', 'medium', true, ARRAY['battle ropes']::text[], 'Conditioning', 'Andy''s library'),
  ('Bicep Curls', 'max_strength', 'arms', 'pull', 'low', false, ARRAY['dumbbells']::text[], NULL, 'Andy''s library'),
  ('DB Bent-Over Row', 'max_strength', 'back', 'pull', 'medium', false, ARRAY['dumbbell']::text[], NULL, 'Andy''s library'),
  ('Chest-Supported Row', 'max_strength', 'back', 'pull', 'medium', true, ARRAY['dumbbells', 'bench']::text[], 'No spinal loading', 'VJB'),
  ('Face Pull', 'max_strength', 'shoulders', 'pull', 'low', true, ARRAY['cable machine']::text[], 'Shoulder health', NULL),
  ('Floor Press', 'max_strength', 'chest', 'push', 'medium', true, ARRAY['barbell']::text[], 'Shoulder-friendly. Limits ROM', 'Shoulder mod'),
  ('Incline DB Press (neutral grip)', 'max_strength', 'chest', 'push', 'medium', true, ARRAY['dumbbells', 'incline bench']::text[], 'Neutral grip protects shoulder', 'Shoulder mod'),
  ('Lat Pulldown', 'max_strength', 'back', 'pull', 'medium', true, ARRAY['cable machine']::text[], NULL, NULL),
  ('Horse Stance Hold', 'max_strength', 'hips', 'squat', 'medium', true, ARRAY['bodyweight']::text[], 'Start 3-step, progress to 50% BW, then 5-step', 'Andy''s library'),
  ('Horse Stance Squats', 'max_strength', 'hips', 'squat', 'medium', true, ARRAY['bodyweight']::text[], 'Dynamic version of horse stance', 'Flex menu'),
  ('Seated Good Morning', 'max_strength', 'hamstrings', 'hinge', 'medium', true, ARRAY['barbell']::text[], NULL, 'Andy''s library'),
  ('Jefferson Curl', 'max_strength', 'hamstrings', 'hinge', 'medium', true, ARRAY['barbell']::text[], 'Controlled spinal flexion with weight', 'Andy''s library'),
  ('Copenhagen Lift', 'max_strength', 'hips', 'mobility', 'medium', true, ARRAY['bench']::text[], 'Side plank with adductor focus', 'Andy''s library'),
  ('Elevated Pigeon Good Morning', 'max_strength', 'glutes', 'hinge', 'medium', false, ARRAY['bodyweight']::text[], 'Pigeon position + forward fold', 'Flex menu'),
  ('Side Split Push-Ups', 'max_strength', 'hips', 'push', 'medium', true, ARRAY['bodyweight']::text[], 'Push-up with wide side split stance', 'Flex menu'),
  ('Straddle Leg Lifts', 'max_strength', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Flex menu'),
  ('Side Split Isometric Hold', 'skill', 'hips', 'mobility', 'medium', true, ARRAY['blocks']::text[], 'Extend to max, hold 8s, contract, relax', 'Andy''s library'),
  ('Frog Pose PNF', 'skill', 'hips', 'mobility', 'medium', true, ARRAY['bodyweight']::text[], 'Contract 10s, relax 5s', 'Andy''s library'),
  ('Pissing Dog', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], 'In frog pose, extend leg out', 'Andy''s library'),
  ('Abductor Rocks', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('L-Lifts', 'skill', 'hips', 'mobility', 'medium', true, ARRAY['bodyweight']::text[], 'Targets active hip flexion', 'Andy''s library'),
  ('Front Split CRAC', 'skill', 'hips', 'mobility', 'medium', true, ARRAY['bodyweight']::text[], 'Contract-Relax-Agonist-Contract', 'Flex menu'),
  ('ISO Side Split Reps', 'skill', 'hips', 'mobility', 'medium', true, ARRAY['bodyweight']::text[], '5s holds at max range', 'Flex menu'),
  ('Wall Hip Flexor PNF', 'skill', 'hips', 'mobility', 'medium', true, ARRAY['wall']::text[], 'PNF contract-relax against wall', 'Flex menu'),
  ('Frog Stretch', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Hamstring Stretch', 'skill', 'hamstrings', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Couch Stretch', 'skill', 'hips', 'mobility', 'low', false, ARRAY['couch', 'wall']::text[], NULL, 'Andy''s library'),
  ('Warrior (Hip Flexor) Stretch', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Glute Stretch', 'skill', 'glutes', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Side Split Stretch', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Front Split Stretch', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Butterfly Stretch', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Kneeling Hip Flexor Stretch', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], 'Dynamic version for warm-up', 'Flex menu'),
  ('Banded Side Leg Raise', 'skill', 'hips', 'mobility', 'low', false, ARRAY['band']::text[], NULL, 'Andy''s library'),
  ('Banded Walks', 'skill', 'glutes', 'mobility', 'low', true, ARRAY['band']::text[], 'Hip activation', 'Andy''s library'),
  ('Clamshell', 'skill', 'glutes', 'mobility', 'low', false, ARRAY['band']::text[], 'Hip activation, external rotators', 'Andy''s library'),
  ('Crab Walks', 'skill', 'glutes', 'mobility', 'low', true, ARRAY['band']::text[], 'Hip activation', 'Andy''s library'),
  ('Hip Flexor Raise', 'skill', 'hips', 'mobility', 'low', false, ARRAY['ankle weight']::text[], 'Ankle weight + elevated platform', 'Andy''s library'),
  ('Weighted Butterfly', 'max_strength', 'hips', 'mobility', 'low', true, ARRAY['dumbbell']::text[], NULL, 'Andy''s library'),
  ('Weighted Side-Abductor Lift', 'max_strength', 'hips', 'mobility', 'low', false, ARRAY['ankle weight']::text[], NULL, 'Andy''s library'),
  ('Chamber Tucks', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Front Kick Extensions', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], 'Teep forward', 'Andy''s library'),
  ('Kneeling Round Kick', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Standing Chamber Pulses', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Kneeling Windshield Wipers', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('90-90 Switches', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], 'Hip rotation drill', 'Andy''s library'),
  ('Car 90-90', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], 'Seated, 90-90 position, lift and rotate', 'Andy''s library'),
  ('Duck Walk', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Hip Airplanes', 'skill', 'hips', 'mobility', 'low', false, ARRAY['bodyweight']::text[], 'Hip rotation', 'Andy''s library'),
  ('Lying Hip Circles', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Squat to Rotation', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], 'Thoracic/hip combined', 'Andy''s library'),
  ('Half Kneeling Cossack Hinge', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Internal Rotation in 90-Sit', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Half Kneeling Tootsie Rolls', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library'),
  ('Sumo Squat Knee Twisting Drop', 'skill', 'hips', 'mobility', 'low', true, ARRAY['bodyweight']::text[], NULL, 'Andy''s library')
ON CONFLICT (name) DO UPDATE SET
  training_quality = EXCLUDED.training_quality,
  muscle_group     = EXCLUDED.muscle_group,
  movement_pattern = EXCLUDED.movement_pattern,
  intensity_tier   = EXCLUDED.intensity_tier,
  bilateral        = EXCLUDED.bilateral,
  equipment        = EXCLUDED.equipment,
  notes            = EXCLUDED.notes,
  source           = EXCLUDED.source;
