-- V1 backend automation: SMS inbox/outbox + weekly digest + block retro
-- Closes A24-299, A24-300, A24-304, A24-305 (schema portion).
--
-- All four tables follow the existing v0 conventions:
--   - uuid PKs
--   - created_at/updated_at with set_updated_at trigger
--   - RLS disabled (solo v0 mode)
--   - grants for anon, authenticated, service_role

-- ===== sms_inbox =====
-- Raw inbound SMS landing zone. Persisted BEFORE any parsing so we never
-- lose data even if the parser blows up downstream.
create table if not exists public.sms_inbox (
  id uuid primary key default gen_random_uuid(),
  received_at timestamptz not null default now(),
  from_number text not null,
  body text not null,
  -- received → parsing → parsed | failed
  status text not null default 'received'
    check (status in ('received', 'parsing', 'parsed', 'failed', 'ignored')),
  intent text,          -- 'workout_log' | 'bodyweight' | 'help' | 'other'
  parse_result jsonb,   -- structured output from Claude tool call
  parse_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sms_inbox_received_at_idx
  on public.sms_inbox (received_at desc);
create index if not exists sms_inbox_status_idx
  on public.sms_inbox (status);

drop trigger if exists sms_inbox_set_updated_at on public.sms_inbox;
create trigger sms_inbox_set_updated_at
before update on public.sms_inbox
for each row execute function public.set_updated_at();

-- ===== sms_sent =====
-- Outbound SMS log — daily session sends, confirmations, digest summaries.
-- Used for cron idempotency (daily sender dedup, digest dedup).
create table if not exists public.sms_sent (
  id uuid primary key default gen_random_uuid(),
  sent_at timestamptz not null default now(),
  to_number text not null,
  body text not null,
  kind text not null,   -- 'daily_session' | 'confirmation' | 'bw_ack' | 'sunday_digest' | 'block_retro' | 'reject'
  -- For idempotency: kind + dedup_key uniqueness lets us answer
  -- "did we already send today's session?"
  dedup_key text,
  linq_message_id text,
  linq_status int,
  linq_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kind, dedup_key)
);

create index if not exists sms_sent_sent_at_idx
  on public.sms_sent (sent_at desc);
create index if not exists sms_sent_kind_idx
  on public.sms_sent (kind, sent_at desc);

drop trigger if exists sms_sent_set_updated_at on public.sms_sent;
create trigger sms_sent_set_updated_at
before update on public.sms_sent
for each row execute function public.set_updated_at();

-- ===== weekly_digests =====
-- Sunday-morning auto-generated weekly review. Persisted for history +
-- so the dashboard `/review` page can render past digests.
create table if not exists public.weekly_digests (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,  -- Sunday of the digest week
  athlete_slug text not null default 'andy',
  arc_slug text not null,
  sms_summary text not null,        -- short version (delivered via SMS)
  email_body text,                  -- long-form markdown for email
  metrics jsonb,                    -- raw numbers backing the digest
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists weekly_digests_week_start_idx
  on public.weekly_digests (week_start desc);

drop trigger if exists weekly_digests_set_updated_at on public.weekly_digests;
create trigger weekly_digests_set_updated_at
before update on public.weekly_digests
for each row execute function public.set_updated_at();

-- ===== block_retros =====
-- End-of-block retro. Generated by cron on last day of each block.
create table if not exists public.block_retros (
  id uuid primary key default gen_random_uuid(),
  block_slug text not null unique,  -- e.g. '2026-05-block-01-power-conversion'
  athlete_slug text not null default 'andy',
  arc_slug text not null,
  block_start date,
  block_end date,
  goal_verdicts jsonb,              -- [{goal: 'G1', verdict: 'hit'|'partial'|'miss', evidence: '...'}]
  observations text,
  next_block_adjustments text,
  email_body text,
  sms_summary text,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists block_retros_block_end_idx
  on public.block_retros (block_end desc);

drop trigger if exists block_retros_set_updated_at on public.block_retros;
create trigger block_retros_set_updated_at
before update on public.block_retros
for each row execute function public.set_updated_at();

-- ===== RLS disabled (solo v0 mode) =====
alter table public.sms_inbox       disable row level security;
alter table public.sms_sent        disable row level security;
alter table public.weekly_digests  disable row level security;
alter table public.block_retros    disable row level security;

-- ===== Grants =====
grant select, insert, update, delete on table
  public.sms_inbox,
  public.sms_sent,
  public.weekly_digests,
  public.block_retros
to anon, authenticated, service_role;
